# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: UCOSP
email: ucosp-steering@ucosp.ca
description: > # this means to ignore newlines until "baseurl:"
    Undergraduate Capstone Open Source Projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ucosp.github.io" # the base hostname & protocol for your site
twitter_username: ucosp
github_username:  ucosp

github: ''

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# The 'comments' setting enables comments. You'll need to select either
# disqus or isso below to choose a comment system. Individual posts can
# override 'comments' to disable on a post-by-post basis.
comments: true

# Set this to your public isso URL to enable comments via isso. Set to '' to disable isso.
isso: ''

# Set this to your disqus shortname to enable comments via disqus. Set to '' to disable disqus.
disqus: ''

permalink: /:year/:month/:title
paginate: 3

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate', 'jekyll-feed']

exclude: ['README.md', 'LICENSE']

